version: "3.9"

services:
  app:
    build: .
    container_name: xquantify_app
    env_file: .env
    command: uvicorn main:app --host 0.0.0.0 --port ${APP_PORT:-8000} --workers 2
    ports:
      - "${APP_PORT:-8000}:8000"
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: xquantify_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: